#!/usr/bin/env tsx
/**
 * new:route — create a new route in `/product/pages/` + a thin shim under
 * `/app/`. The shim does nothing but re-export the product page, so the
 * Next.js router finds it while the actual page code lives in the region
 * the user is allowed to edit.
 *
 * Usage:
 *   pnpm new:route /app/(authed)/app/settings
 *
 * Produces:
 *   app/(authed)/app/settings/page.tsx              ← shim (don't edit)
 *   product/pages/(authed)/app/settings/page.tsx    ← edit this
 *
 * The shim uses the `@/product/*` path alias wired up in tsconfig.json.
 * Matches the shim convention established for platform routes in
 * Tranche 11b-2 Phase C (export * + export { default }).
 */
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(SCRIPT_DIR, "..");

function usage(): never {
  console.error("Usage: pnpm new:route <route-path>");
  console.error("");
  console.error("  <route-path> is the URL-like path under /app/, e.g.");
  console.error("    /app/(authed)/app/settings");
  console.error("    /app/(marketing)/blog/[slug]");
  console.error("");
  console.error("The corresponding page file is created under");
  console.error("/product/pages/ with the same path (route groups preserved).");
  process.exit(1);
}

function main(): void {
  const args = process.argv.slice(2);
  if (args.length !== 1) usage();

  const raw = args[0];
  // Accept "/app/..." or "app/..."; strip a leading slash.
  const routePath = raw.replace(/^\/+/, "");
  if (!routePath.startsWith("app/")) {
    console.error(
      `Route path must start with "app/" (got: "${routePath}"). New routes always live under /app/ at the repo root.`,
    );
    process.exit(1);
  }

  // Shim path: literal route under /app/.
  // Page path: same path but under /product/pages/ (route groups + dynamic
  // segments preserved exactly).
  const shimRel = `${routePath}/page.tsx`;
  const pageRel = routePath.replace(/^app\//, "product/pages/") + "/page.tsx";

  const shimAbs = join(REPO_ROOT, shimRel);
  const pageAbs = join(REPO_ROOT, pageRel);

  if (existsSync(shimAbs)) {
    console.error(`Route already exists: ${shimRel}`);
    process.exit(1);
  }
  if (existsSync(pageAbs)) {
    console.error(`Page file already exists: ${pageRel}`);
    process.exit(1);
  }

  // The import target — strip the trailing ".tsx" extension. The `@/product/*`
  // alias is wired in tsconfig.json since Tranche 11b-2 Phase A.
  const importTarget = "@/" + pageRel.replace(/\.tsx$/, "");

  const shimContent = [
    `// AUTO-GENERATED by \`pnpm new:route\`. This file is a routing shim — the`,
    `// real page lives in /product/pages/. Don't edit this file; edit the page`,
    `// file instead.`,
    `//`,
    `// To remove this route, delete BOTH this file and the page file:`,
    `//   ${pageRel}`,
    ``,
    `export * from "${importTarget}";`,
    `export { default } from "${importTarget}";`,
    ``,
  ].join("\n");

  const pageTitle = routePath.split("/").pop() ?? "page";
  const pageContent = [
    `// Page component for /${routePath}.`,
    `// This file is in /product/ — modify freely.`,
    ``,
    `export default function Page() {`,
    `  return (`,
    `    <section className="container max-w-3xl space-y-4 py-12">`,
    `      <h1 className="text-3xl font-semibold tracking-tight">${pageTitle}</h1>`,
    `      <p className="text-muted-foreground">`,
    `        Replace this stub with your actual page.`,
    `      </p>`,
    `    </section>`,
    `  );`,
    `}`,
    ``,
  ].join("\n");

  mkdirSync(dirname(shimAbs), { recursive: true });
  writeFileSync(shimAbs, shimContent, "utf-8");

  mkdirSync(dirname(pageAbs), { recursive: true });
  writeFileSync(pageAbs, pageContent, "utf-8");

  console.log(`✓ created route /${routePath}`);
  console.log(`  shim:  ${shimRel}`);
  console.log(`  page:  ${pageRel}`);
  console.log(``);
  console.log(`Edit ${pageRel} to build your page.`);
}

main();
