#!/usr/bin/env tsx
/**
 * sync-ai-rules
 *
 * Parses scripts/ai-rules.source.md (the single source of truth) and
 * regenerates the per-tool and per-region rule files. Designed to be run
 * via `pnpm sync-ai-rules`.
 *
 * Section model: the source file is split on level-2 headings (`## `).
 * The script knows which sections belong in which output file and composes
 * them. The exact heading text matters — see SECTION_KEYS below.
 *
 * Generated files are clobbered on every run. The header banner at the top
 * of each output makes that obvious to anyone who opens one.
 */
import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

// ─── Locate repo root ────────────────────────────────────────────
const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(SCRIPT_DIR, "..");
const SOURCE_PATH = join(SCRIPT_DIR, "ai-rules.source.md");

// ─── Section keys (must match `## ` headings in the source) ─────
const SECTION_KEYS = {
  global: "Global rules (apply everywhere)",
  platform: "Region: /platform/",
  website: "Region: /website/",
  product: "Region: /product/",
  forbidden: "Forbidden patterns",
  required: "Required patterns",
} as const;
type SectionKey = keyof typeof SECTION_KEYS;

// ─── Parse the source into a section → body map ──────────────────
function parseSections(md: string): Map<string, string> {
  const sections = new Map<string, string>();
  const lines = md.split("\n");
  let current: { heading: string; body: string[] } | null = null;

  for (const line of lines) {
    if (line.startsWith("## ")) {
      if (current) {
        sections.set(current.heading, current.body.join("\n").trim());
      }
      current = { heading: line.slice(3).trim(), body: [] };
    } else if (current) {
      current.body.push(line);
    }
  }
  if (current) sections.set(current.heading, current.body.join("\n").trim());
  return sections;
}

// ─── Compose helpers ─────────────────────────────────────────────
function compose(
  sections: Map<string, string>,
  keys: readonly SectionKey[],
): string {
  const parts: string[] = [];
  for (const key of keys) {
    const heading = SECTION_KEYS[key];
    const body = sections.get(heading);
    if (body && body.length > 0) {
      parts.push(`## ${heading}\n\n${body}`);
    }
  }
  return parts.join("\n\n");
}

const BANNER = (relPath: string) =>
  [
    `<!-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ -->`,
    `<!-- AUTO-GENERATED by \`pnpm sync-ai-rules\`. DO NOT EDIT BY HAND.    -->`,
    `<!-- Source: scripts/ai-rules.source.md  •  Target: ${relPath}`,
    `<!-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ -->`,
    ``,
  ].join("\n");

interface CursorFrontmatter {
  description: string;
  globs: string[];
  alwaysApply: boolean;
}
function cursorFrontmatter(fm: CursorFrontmatter): string {
  return [
    `---`,
    `description: ${fm.description}`,
    `globs: ${JSON.stringify(fm.globs)}`,
    `alwaysApply: ${fm.alwaysApply}`,
    `---`,
    ``,
  ].join("\n");
}

// ─── Output spec ─────────────────────────────────────────────────
// Root files = global + every region + forbidden + required (the whole picture).
// Region files = global + that region + forbidden + required.
type OutputKind = "markdown" | "mdc-master" | "mdc-region";

interface Output {
  path: string; // relative to repo root
  kind: OutputKind;
  keys: readonly SectionKey[];
  cursor?: CursorFrontmatter; // only for mdc-* kinds
}

const ROOT_KEYS = [
  "global",
  "platform",
  "website",
  "product",
  "forbidden",
  "required",
] as const;

const REGION_KEYS = (region: "platform" | "website" | "product") =>
  ["global", region, "forbidden", "required"] as const;

const OUTPUTS: Output[] = [
  // ── Root / repo-wide ──
  { path: "CLAUDE.md", kind: "markdown", keys: ROOT_KEYS },
  { path: ".cursorrules", kind: "markdown", keys: ROOT_KEYS },
  {
    path: ".cursor/rules/master.mdc",
    kind: "mdc-master",
    keys: ROOT_KEYS,
    cursor: {
      description: "Master AI rules for the platform repo",
      globs: ["**/*"],
      alwaysApply: true,
    },
  },
  {
    path: ".github/copilot-instructions.md",
    kind: "markdown",
    keys: ROOT_KEYS,
  },
  { path: "AI_INSTRUCTIONS.md", kind: "markdown", keys: ROOT_KEYS },
  // ── /platform/ ──
  {
    path: "platform/CLAUDE.md",
    kind: "markdown",
    keys: REGION_KEYS("platform"),
  },
  {
    path: "platform/.cursor/rules/platform.mdc",
    kind: "mdc-region",
    keys: REGION_KEYS("platform"),
    cursor: {
      description: "AI rules for code in /platform/",
      globs: ["platform/**/*"],
      alwaysApply: true,
    },
  },
  // ── /website/ ──
  {
    path: "website/CLAUDE.md",
    kind: "markdown",
    keys: REGION_KEYS("website"),
  },
  {
    path: "website/.cursor/rules/website.mdc",
    kind: "mdc-region",
    keys: REGION_KEYS("website"),
    cursor: {
      description: "AI rules for code in /website/",
      globs: ["website/**/*"],
      alwaysApply: true,
    },
  },
  // ── /product/ ──
  {
    path: "product/CLAUDE.md",
    kind: "markdown",
    keys: REGION_KEYS("product"),
  },
  {
    path: "product/.cursor/rules/product.mdc",
    kind: "mdc-region",
    keys: REGION_KEYS("product"),
    cursor: {
      description: "AI rules for code in /product/",
      globs: ["product/**/*"],
      alwaysApply: true,
    },
  },
];

// ─── Main ────────────────────────────────────────────────────────
function main(): void {
  if (!existsSync(SOURCE_PATH)) {
    console.error(`Source file not found: ${SOURCE_PATH}`);
    process.exit(1);
  }

  const sections = parseSections(readFileSync(SOURCE_PATH, "utf-8"));

  // Sanity-check that every expected section exists in the source.
  for (const key of Object.values(SECTION_KEYS)) {
    if (!sections.has(key)) {
      console.error(`Source is missing required section: ## ${key}`);
      process.exit(1);
    }
  }

  for (const out of OUTPUTS) {
    const composed = compose(sections, out.keys);
    let content = `${BANNER(out.path)}${composed}\n`;
    if (out.kind === "mdc-master" || out.kind === "mdc-region") {
      if (!out.cursor) {
        console.error(`Missing cursor frontmatter for ${out.path}`);
        process.exit(1);
      }
      content = `${cursorFrontmatter(out.cursor)}${content}`;
    }

    const target = join(REPO_ROOT, out.path);
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, content, "utf-8");
    console.log(`  ✓ ${out.path}`);
  }

  console.log(
    `\nGenerated ${OUTPUTS.length} file${OUTPUTS.length === 1 ? "" : "s"} from scripts/ai-rules.source.md`,
  );
}

main();
